
version: '3.8'
services:
  ai-forensics:
    build: .
    container_name: ai-forensics-app
    ports:
      - "6080:6080"
      - "5901:5901"
    volumes:
      - .:/app  # Mount the project directory
      - /:/host  # Mount the entire local file system (use with caution)
    working_dir: /app
      - $HOME:/host_files
    environment:
      - DISPLAY=host.docker.internal:0.0  # Set DISPLAY variable for Windows
      - MPLBACKEND=TkAgg  # Ensure Matplotlib GUI works inside the container
    command: ["python", "main.py"]
      - VNC_PASSWORD=vncpassword
    stdin_open: true
    tty: true
