version: '3'
services:
  guacamole:
    image: guacamole/guacamole
    ports:
      - "8080:8080"
    environment:
      - GUACD_HOSTNAME=guacd
  guacd:
    image: guacamole/guacd
    restart: always
