version: '3.8'
services:
  ai-forensics:
    build: .
    ports:
      - "6080:6080"
      - "5901:5901"
    volumes:
      - $HOME:/host_files
    environment:
      - VNC_PASSWORD=vncpassword
    stdin_open: true
    tty: true
