
version: '3.8'
services:
  ai-forensics:
    build: .
    container_name: ai-forensics-app
    ports:
      - "6080:6080"
      - "5901:5901"
    volumes:
      - .:/app  # Mount the project directory
      - /:/host  # Mount the entire local file system (use with caution)
      - $HOME:/host_files

    working_dir: /app
      - $HOME:/host_files
    environment:
      - DISPLAY=${DISPLAY:-host.docker.internal:0.0}  # Fall back to Windows-style DISPLAY
      - MPLBACKEND=TkAgg  # Ensure Matplotlib GUI works inside the container
      - VNC_PASSWORD=${VNC_PASSWORD:-vncpassword}  # Default to 'vncpassword'
    command: ["python", "main.py"]
      - VNC_PASSWORD=vncpassword
    stdin_open: true
    tty: true
